#!/usr/bin/env python3
"""Generate the macOS guest image's host-import doorbell stubs.

Each import's stub stores the import's index to a doorbell guest address
(the image's own __host_doorbell page, in guest memory) and returns. The
store faults (the doorbell is deliberately unmapped in the host's stage-2
page tables... see port/macos/README.md: it IS mapped read-only as a
dummy), no — the doorbell page is mapped with WRITE permission CLEARED, so
a store exits the vCPU with a data abort whose IPA identifies the import.
The host services the call and re-executes the store with permissions
granted (then re-revoked), so the stub is a plain str; the arguments stay
in their registers untouched.

The stub for import N:
    movz x17, #(DOORBELL + N*4) & 0xffff
    movk x17, #(DOORBELL + N*4) >> 16, lsl #16
    str wzr, [x17]
    ret

x17 is the intra-procedure scratch register (intra-call clobber), which is
exactly what a stub may trash. Doorbell addresses live below 4 GB with the
rest of the guest's view of the machine (the game's data structures assume
32-bit pointers, and the doorbell pointer must survive the same code).

Usage: macos_imports.py [--doorbell IPA] output.s list...
"""

import sys

DOORBELL = 0x10000000  # guest address of the doorbell page (below 4 GB)


def main():
    arguments = sys.argv[1:]
    global DOORBELL
    if arguments[0] == "--doorbell":
        DOORBELL = int(arguments[1], 0)
        arguments = arguments[2:]
    output, lists = arguments[0], arguments[1:]
    names = []
    for path in lists:
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line and line not in names:
                names.append(line)
    out = ["/* generated by tools/macos_imports.py; do not edit */", "\t.text"]
    for index, name in enumerate(names):
        address = DOORBELL + index * 4
        low = address & 0xFFFF
        high = (address >> 16) & 0xFFFF
        out += [
            f"\t.globl {name}",
            f"\t.type {name},%function",
            "\t.p2align 2",
            f"{name}:",
            f"\tmovz x17, #{low:#x}",
            f"\tmovk x17, #{high:#x}, lsl #16",
            "\tstr wzr, [x17]",
            "\tret",
        ]
    out += [
        "\t.section .rodata",
        "\t.globl __host_import_names",
        "__host_import_names:",
    ]
    out += [f'\t.asciz "{name}"' for name in names]
    out += [
        "\t.p2align 2",
        "\t.globl __host_import_count",
        "__host_import_count:",
        f"\t.long {len(names)}",
        "\t.data",
        "\t.p2align 3",
        "\t.globl __host_import_table",
        "__host_import_table:",
        f"\t.zero {max(len(names), 1) * 8}",
    ]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(names)} imports")


if __name__ == "__main__":
    main()