#!/usr/bin/env python3
"""Generate the macOS host's doorbell dispatch: for every guest import
(the Android lists, which the guest's stubs were generated from) a typed
wrapper that moves the guest's registers into a C call, runs the macOS
host's implementation, and writes the result back.

The Android host calls its functions directly (one address space); here
the registers cross the vCPU boundary, so each wrapper marshals them:
32-bit integers are masked (the guest's registers are the low words of
64-bit ones), long longs pass whole, and floats/doubles move through the
SIMD registers, which the hypervisor saves and restores with the vCPU.

Usage: macos_import_dispatch.py --list host.h output.c
       (host.h declares the host functions; the import names come from
       the .list files of tools/macos_imports.py's callers)
"""

import re
import sys

# the host functions this port provides (host.h's declarations), with the
# import name for each; GL imports (hostgl_*) resolve at run time and the
# stub generators' guest wrappers widen their arguments already


def parse_header(path):
    text = open(path, encoding="utf-8").read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    result = {}
    for m in re.finditer(r"^([A-Za-z_][\w \*]*?)\b(\w+)\s*\(([^;]*?)\)\s*(?:__attribute__\(\(.*?\)\)\s*)?;", text, re.M | re.S):
        ret, name, params = m.group(1).strip(), m.group(2), " ".join(m.group(3).split())
        result[name] = (ret, params)
    return result


def main():
    arguments = sys.argv[1:]
    lists = []
    headers = []
    output = None
    i = 0
    while i < len(arguments):
        if arguments[i] == "--list":
            lists.append(arguments[i + 1])
            i += 2
        elif arguments[i] == "--header":
            headers.append(arguments[i + 1])
            i += 2
        else:
            output = arguments[i]
            i += 1
    names = []
    for path in lists:
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line and line not in names:
                names.append(line)
    protos = {}
    for h in headers:
        protos.update(parse_header(h))

    out = [
        "/* generated by tools/macos_import_dispatch.py; do not edit */",
        '#include "host.h"',
        "#include <string.h>",
        '#include "posix.h"',
        "",
        "",
    ]

    # the C type of each import: the guest_host.h rules (32-bit int, long
    # long for 64-bit, pointers as pointers)
    def host_function(import_name):
        if import_name.startswith("hostposix_"):
            return "posix_" + import_name[len("hostposix_"):]
        if import_name.startswith("hostgl_"):
            return None  # resolved at run time
        return import_name

    def wrapper(import_name):
        fn = host_function(import_name)
        if not fn:
            return None
        if fn not in protos:
            return None
        ret, params = protos[fn]
        if params in ("void", ""):
            plist = []
        else:
            plist = []
            for p in params.split(","):
                p = " ".join(p.split())
                m = re.match(r"(.*?)(\w+)\s*$", p)
                if m:
                    plist.append((m.group(1).strip(), m.group(2)))
        lines = []
        call_args = []
        simd_loads = []
        simd_stores = []
        for index, (ptype, pname) in enumerate(plist):
            reg = f"x[{index}]"
            if "*" in ptype:
                call_args.append(f"({ptype})(uintptr_t)R->{reg}")
            elif ptype in ("long long", "unsigned long long", "int64_t", "uint64_t"):
                call_args.append(f"({ptype})R->{reg}")
            elif ptype in ("float", "double"):
                call_args.append(f"S{index}")
                simd_loads.append(f"\tmemcpy(&S{index}, &Q[{index}], sizeof(S{index}));")
            elif ptype.startswith("unsigned"):
                call_args.append(f"({ptype})R->{reg}")
            elif ptype == "_Bool" or ptype == "bool":
                call_args.append(f"(_Bool)R->{reg}")
            else:
                call_args.append(f"({ptype})R->{reg}")
        if ret in ("float", "double"):
            simd_stores.append("\tmemcpy(&Q[0], &host_result, sizeof(host_result));")
        body_ret = ret if ret != "void" else "void"
        lines.append(f"static void {import_name}_wrapper(void)")
        lines.append("{")
        lines.append("\tstruct guest_registers *R = host_vcpu_dispatch_registers();")
        if simd_loads or simd_stores:
            lines.append("\tunsigned char Q[8][16];")
        if ret != "void":
            lines.append(f"\t{body_ret} host_result;")
        for load in simd_loads:
            lines.append(load)
        call = f"{fn}({', '.join(call_args)})"
        if ret != "void":
            lines.append(f"\thost_result = {call};")
        else:
            lines.append(f"\t{call};")
        for store in simd_stores:
            lines.append(store)
        if ret != "void":
            if ret in ("long long", "unsigned long long", "int64_t", "uint64_t") or "*" in ret:
                lines.append("\tR->x[0] = (uint32_t)(uint64_t)(uintptr_t)host_result;")
            elif ret == "float" or ret == "double":
                pass
            else:
                lines.append("\tR->x[0] = (uint32_t)host_result;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    wrappers = []
    table = []
    externs = []
    for name in names:
        if name.startswith("hostgl_"):
            # GL: the hypervisor path also crosses for these; the host
            # resolves the entry point at run time and the wrapper calls it
            # with the (already widened) arguments, through a trampoline
            # generated by tools/macos_gl_dispatch.py
            externs.append(f"void {name}_trampoline(void);")
            table.append(f'\t{{ "{name}", {name}_trampoline }},')
            continue
        w = wrapper(name)
        if not w:
            print(f"{name}: no host declaration; add one to the header", file=sys.stderr)
            continue
        wrappers.append(w)
        table.append(f'\t{{ "{name}", {name}_wrapper }},')
    out += externs
    out += wrappers
    out += [
        "const struct import_entry host_import_table[] =",
        "{",
        *table,
        "};",
        "",
        f"const unsigned host_import_count = sizeof(host_import_table) / sizeof(host_import_table[0]);",
        "",
    ]
    if not output:
        raise SystemExit("no output file")
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(table)} dispatch entries")


if __name__ == "__main__":
    main()