#!/usr/bin/env python3
"""Generate the macOS host's wrappers of the functions the guest imports.

The Android host can let the guest call OpenGL ES and port/linux/src/posix.h
directly: guest pointers are host addresses there. The macOS guest's 4 GB
lie at a base address instead (port/macos/README.md), so each pointer the
guest passes must have the base added. For every function the guest imports
this writes a host function of the import's name that does so and calls the
real one:

- hostgl_<function> for the OpenGL functions in port/linux/src/gl.h's list,
  with the parameters tools/android_gl_stubs.py's guest side passes (its
  widened integers and stack pointers included); host_gl_resolve
  (port/macos/host/host_gl.c) finds them by name, and they call the
  system's OpenGL through pointers it resolves;
- hostposix_<name> for port/linux/src/posix.h's posix_<name>, which the host
  is linked with.

Pointers that are not addresses pass unchanged: the offsets into the bound
buffer that glVertexAttribPointer and glDrawElements take, and posix.h's
directory handles.

Usage: macos_host_wrappers.py gl gl.h gl32.h gl2ext.h output.c
       macos_host_wrappers.py posix posix.h output.c
"""

import re
import sys

from android_gl_stubs import (FLOAT_TYPES, INTEGER_REGISTER_COUNT, WIDE_TYPES, android_functions, prototypes,
                              split_parameter)

# (function, parameter index): an offset into the bound buffer
GL_OFFSETS = {
    ("glVertexAttribPointer", 5), ("glVertexAttribIPointer", 4),
    ("glDrawElements", 3), ("glDrawElementsBaseVertex", 3),
}

# what OpenGL 4.1 lacks of the list, which these stand in for
GL_FALLBACKS = {
    # (only a hint)
    "glInvalidateFramebuffer": "",
    # (the renderer does without, xgpu_capabilities.copy_image)
    "glCopyImageSubData": "",
}


def gl_wrappers(gl_header: str, gl32: str, gl2ext: str) -> str:
    functions = android_functions(gl_header)
    protos = prototypes(gl32, gl2ext)
    out = [
        "/* generated by tools/macos_host_wrappers.py from port/linux/src/gl.h; do not edit */",
        "#define GL_GLES_PROTOTYPES 1",
        "#include <GLES3/gl32.h>",
        "#include <GLES2/gl2ext.h>",
        "#include <dlfcn.h>",
        "#include <string.h>",
        '#include "host.h"',
        "",
    ]
    names = []
    for name in functions:
        if name == "glGetString":
            # (host_gl_get_string copies the text into guest memory)
            continue
        ret, params = protos[name]
        plist = [] if params in ("void", "") else [split_parameter(p) for p in params.split(",")]
        out.append(f"static __typeof__(&{name}) real_{name};")
        if name == "glShaderSource":
            out += [
                "void hostgl_glShaderSource(GLuint shader, GLsizei count, uint32_t strings, uint32_t lengths)",
                "{",
                "\tconst unsigned long long *guest_strings = G2H(strings);",
                "\tconst GLchar *host_strings[16];",
                "\tGLsizei index;",
                "",
                "\tif (count > 16)",
                "\t\tcount = 16;",
                "\tfor (index = 0; index < count; index++)",
                "\t\thost_strings[index] = G2H(guest_strings[index]);",
                "\treal_glShaderSource(shader, count, host_strings, G2H(lengths));",
                "}",
                "",
            ]
            names.append(name)
            continue
        host_params, call_args = [], []
        integer_index = 0
        for index, (ptype, _) in enumerate(plist):
            arg = f"a{index}"
            is_pointer = "*" in ptype
            base = ptype.replace("const", "").strip()
            if base in FLOAT_TYPES and not is_pointer:
                host_params.append(f"{ptype} {arg}")
                call_args.append(arg)
                continue
            wide = base in WIDE_TYPES and not is_pointer
            on_stack = integer_index >= INTEGER_REGISTER_COUNT
            integer_index += 1
            if is_pointer:
                # (the guest's side passes one on the stack widened)
                host_params.append(f"{'uint64_t' if on_stack else 'uint32_t'} {arg}")
                if (name, index) in GL_OFFSETS:
                    call_args.append(f"({ptype})(uintptr_t)(uint32_t){arg}")
                else:
                    call_args.append(f"({ptype})G2H({arg})")
            elif wide or on_stack:
                host_params.append(f"long long {arg}")
                call_args.append(f"({ptype}){arg}")
            else:
                host_params.append(f"{ptype} {arg}")
                call_args.append(arg)
        call = f"real_{name}({', '.join(call_args)})"
        out.append(f"{ret} hostgl_{name}({', '.join(host_params) or 'void'})")
        out.append("{")
        if name in GL_FALLBACKS:
            out.append(f"\tif (!real_{name})")
            out.append("\t\treturn;")
        out.append(f"\t{'return ' if ret != 'void' else ''}{call};")
        out.append("}")
        out.append("")
        names.append(name)
    out += [
        "static const struct { const char *name; void *wrapper; void **real; } gl_functions[] =",
        "{",
    ]
    out += [f'\t{{ "{name}", (void *)hostgl_{name}, (void **)&real_{name} }},' for name in names]
    out += [
        "};",
        "",
        "/* the wrapper of the OpenGL function, its function found first in the",
        "system's OpenGL (or NULL for one it lacks that has no stand-in) */",
        "void *host_gl_wrapper(const char *name)",
        "{",
        "\tunsigned long index;",
        "",
        "\tfor (index = 0; index < sizeof(gl_functions) / sizeof(gl_functions[0]); index++)",
        "\t{",
        "\t\tif (strcmp(gl_functions[index].name, name))",
        "\t\t\tcontinue;",
        "\t\t*gl_functions[index].real = dlsym(RTLD_DEFAULT, name);",
        "\t\tif (!*gl_functions[index].real)",
        "\t\t{",
        f'\t\t\tstatic const char *const fallbacks[] = {{ {", ".join(chr(34) + n + chr(34) for n in GL_FALLBACKS)} }};',
        "\t\t\tunsigned long fallback;",
        "",
        "\t\t\tfor (fallback = 0; fallback < sizeof(fallbacks) / sizeof(fallbacks[0]); fallback++)",
        "\t\t\t{",
        "\t\t\t\tif (!strcmp(fallbacks[fallback], name))",
        "\t\t\t\t\treturn gl_functions[index].wrapper;",
        "\t\t\t}",
        "\t\t\treturn NULL;",
        "\t\t}",
        "\t\treturn gl_functions[index].wrapper;",
        "\t}",
        "\treturn NULL;",
        "}",
    ]
    return "\n".join(out) + "\n"


# posix.h's parameters that are opaque handles, not addresses: (type, name)
POSIX_HANDLES = {("void *", "directory")}

# what the kernel writes into the guest's memory, with its size (a parameter
# or a number of bytes): a page the renderer watches for writes
# (host_memory.c) would fail the call instead of faulting, so it is let go
# of first
POSIX_KERNEL_WRITES = {
    "posix_socket_recv": [("buffer", "length")],
    "posix_socket_recvfrom": [("buffer", "length"), ("address", "128")],
    "posix_socket_accept": [("address", "128")],
    "posix_socket_getsockname": [("address", "128")],
    "posix_socket_getpeername": [("address", "128")],
    "posix_socket_getsockopt": [("value", "16")],
    "posix_discord_read": [("buffer", "length")],
}


def posix_wrappers(header: str) -> str:
    text = open(header, encoding="utf-8").read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    found = re.findall(r"^([A-Za-z_][\w \*]*?)\b(posix_\w+)\s*\(([^;]*?)\);", text, re.M | re.S)
    out = [
        "/* generated by tools/macos_host_wrappers.py from port/linux/src/posix.h; do not edit */",
        '#include "host.h"',
        '#include "posix.h"',
        "",
        "void host_memory_watch_prepare_write(uint32_t address, uint32_t size);",
        "",
    ]
    for ret, name, params in found:
        ret = " ".join(ret.split())
        params = " ".join(params.split())
        host_params, call_args = [], []
        if params != "void":
            for param in params.split(","):
                param = param.strip()
                m = re.match(r"(.*?)(\w+)\s*$", param)
                ptype, pname = m.group(1).strip(), m.group(2)
                handle = (" ".join(ptype.split()), pname) in POSIX_HANDLES
                if "*" in ptype and not handle:
                    host_params.append(f"uint32_t {pname}")
                    call_args.append(f"({ptype})G2H({pname})")
                elif "*" in ptype:
                    host_params.append(f"uint32_t {pname}")
                    call_args.append(f"({ptype})(uintptr_t){pname}")
                else:
                    host_params.append(f"{ptype} {pname}")
                    call_args.append(pname)
        host_name = "hostposix_" + name[len("posix_"):]
        # (a pointer returned is a handle: the guest keeps its 32 bits)
        host_ret = "uint32_t" if "*" in ret else ret
        call = f"{name}({', '.join(call_args)})"
        out.append(f"{host_ret} {host_name}({', '.join(host_params) or 'void'});")
        out.append(f"{host_ret} {host_name}({', '.join(host_params) or 'void'})")
        out.append("{")
        for buffer, size in POSIX_KERNEL_WRITES.get(name, []):
            out.append(f"\tif ({buffer} && (int){size} > 0)")
            out.append(f"\t\thost_memory_watch_prepare_write({buffer}, (uint32_t){size});")
        if ret == "void":
            out.append(f"\t{call};")
        elif "*" in ret:
            out.append(f"\treturn (uint32_t)(uintptr_t){call};")
        else:
            out.append(f"\treturn {call};")
        out.append("}")
        out.append("")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "gl" and len(sys.argv) == 6:
        result = gl_wrappers(*sys.argv[2:5])
        output = sys.argv[5]
    elif len(sys.argv) >= 2 and sys.argv[1] == "posix" and len(sys.argv) == 4:
        result = posix_wrappers(sys.argv[2])
        output = sys.argv[3]
    else:
        print(__doc__)
        sys.exit(2)
    with open(output, "w", encoding="utf-8") as f:
        f.write(result)


if __name__ == "__main__":
    main()
