#!/usr/bin/env python3
"""Generate the macOS host's GL trampoline: for every hostgl_* import, a
function that reads the guest's registers (the dispatch's), calls the GL
entry point resolved by name, and writes the result back.

The guest's wrapper (tools/android_gl_stubs.py) widened the wide integer
arguments already; pointer arguments arrive as guest addresses, which are
host addresses here (the identity map). The result crosses in x0, floats
and doubles in the SIMD registers.

Usage: macos_gl_dispatch.py --list gl_imports.list --protos gl32.h gl2ext.h output.c
"""

import re
import sys


def prototypes(*headers):
    result = {}
    pattern = re.compile(r"GL_APICALL\s+(.+?)\s*GL_APIENTRY\s+(\w+)\s*\((.*?)\);", re.S)
    for header in headers:
        text = open(header, encoding="utf-8").read()
        for ret, name, params in pattern.findall(text):
            result.setdefault(name, (ret.strip(), " ".join(params.split())))
    return result


FLOAT_TYPES = {"GLfloat", "GLclampf", "GLdouble", "GLclampd", "float", "double"}


def split_parameter(param):
    m = re.match(r"(.*?)(\w+)\s*$", param.strip())
    if not m:
        return (param.strip(), None)
    return (m.group(1).strip(), m.group(2))


def main():
    arguments = sys.argv[1:]
    lists, headers, output = [], [], None
    i = 0
    while i < len(arguments):
        if arguments[i] == "--list":
            lists.append(arguments[i + 1]); i += 2
        elif arguments[i] == "--protos":
            headers += arguments[i + 1].split(","); i += 2
        else:
            output = arguments[i]; i += 1
    names = []
    for path in lists:
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line and line not in names:
                names.append(line)
    protos = prototypes(*headers)

    out = [
        "/* generated by tools/macos_gl_dispatch.py; do not edit */",
        '#include "host.h"',
        '#include <string.h>',
        '#include "host_gl_types.h"',
        '#include <GLES3/gl32.h>',
        '#include <GLES2/gl2ext.h>',
        "",
        "",
    ]
    trampolines = []
    for name in names:
        if not name.startswith("hostgl_"):
            continue
        gl_name = name[len("hostgl_"):]
        if gl_name not in protos:
            raise SystemExit(f"{gl_name}: no prototype in the GLES headers")
        ret, params = protos[gl_name]
        plist = [] if params in ("void", "") else [split_parameter(p) for p in params.split(",")]
        call_args = []
        simd = []
        for index, (ptype, pname) in enumerate(plist):
            if ptype in FLOAT_TYPES and "*" not in ptype:
                simd.append(f"\t{ptype} a{index}; memcpy(&a{index}, &q[{index}], sizeof(a{index}));")
                call_args.append(f"a{index}")
            elif "*" in ptype:
                call_args.append(f"(void *)(uintptr_t)R->x[{index}]")
            elif ptype in ("GLsizeiptr", "GLintptr", "GLint64", "GLuint64"):
                call_args.append(f"(long long)R->x[{index}]")
            else:
                call_args.append(f"(unsigned)R->x[{index}]")
        cast = {
            "GLenum": "unsigned", "GLuint": "unsigned", "GLint": "int", "GLsizei": "int",
            "GLboolean": "unsigned", "GLbitfield": "unsigned",
        }
        call_args = [f"({cast.get(a.split('(')[1].split(')')[0], a.split('(')[1].split(')')[0] if '(' in a else a)}){a[a.index(')')+1:]}"
                     if a.startswith("(") else a for a in call_args]
        body = []
        body.append("void " + name + "_trampoline(void)")
        body.append("{")
        body.append("\tstruct guest_registers *R = host_vcpu_dispatch_registers();")
        if simd:
            body.append("\tunsigned char q[8][16];")
        body += simd
        call = f"{gl_name}({', '.join(call_args)})"
        if ret == "void":
            body.append(f"\ttypedef void (*fn_t)({', '.join(p[0] for p in plist) or 'void'});")
            body.append(f"\tfn_t fn = (fn_t)host_gl_resolve(\"{gl_name}\");")
            body.append("\tif (!fn) return;")
            body.append(f"\tfn({', '.join(c.strip() for c in call_args)});")
        else:
            body.append(f"\ttypedef {ret} (*fn_t)({', '.join(p[0] for p in plist) or 'void'});")
            body.append(f"\tfn_t fn = (fn_t)host_gl_resolve(\"{gl_name}\");")
            body.append("\tif (!fn) return;")
            body.append(f"\t{ret} result = fn({', '.join(c.strip() for c in call_args)});")
            if ret in ("float", "double"):
                body.append("\tmemcpy(&q[0], &result, sizeof(result));")
            else:
                body.append("\tR->x[0] = (uint32_t)(uint64_t)result;")
        body.append("}")
        body.append("")
        trampolines.append("\n".join(body))

    out += trampolines
    out += [
        "/* the dispatch's single doorbell for all of them (the entry's name",
        "is in the guest's import names, and the trampoline calls by name) */",
        "void hostgl_trampoline(void)",
        "{",
        "\thost_fatal(\"the guest called hostgl_ through the generic doorbell\");",
        "}",
        "",
    ]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(trampolines)} GL trampolines")


if __name__ == "__main__":
    main()
